In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('product_sales_region.xlsx')
#importing the data

In [4]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [5]:
df.info
#do checks with DISHT with discribe,info,shape,head,tail

<bound method DataFrame.info of            Date   Region  Product  Quantity  UnitPrice StoreLocation  \
0    2023-02-23     East   Laptop        14     163.60       Store B
1    2024-12-19    South    Phone         1     544.01       Store A
2    2023-05-10    North     Desk        14     346.18       Store B
3    2025-02-26  Central    Chair        18     384.82       Store A
4    2023-06-24     East     Desk        18     237.76       Store C
...         ...      ...      ...       ...        ...           ...
1495 2025-02-17     West     Desk        13     134.56       Store D
1496 2024-01-11    South    Chair        18     209.75       Store C
1497 2024-07-27     East     Desk         1     272.50       Store A
1498 2024-12-03  Central  Monitor        14     262.67       Store A
1499 2025-05-09     West    Chair        13     221.39       Store D

     CustomerType  Discount Salesperson  TotalPrice PaymentMethod Promotion  \
0       Wholesale      0.00         Eva    2290.400        Online  FREESHIP
1          Retail      0.00       Alice     544.010     Gift Card    SAVE10
2       Wholesale      0.10       Alice    4361.868        Online  WINTER15
3       Wholesale      0.15       Frank    5887.746     Gift Card  FREESHIP
4          Retail      0.00      Carlos    4279.680        Online    SAVE10
...           ...       ...         ...         ...           ...       ...
1495       Retail      0.05      Carlos    1661.816   Credit Card  WINTER15
1496    Wholesale      0.15       Frank    3209.175    Debit Card  FREESHIP
1497    Wholesale      0.00         Eva     272.500     Gift Card  WINTER15
1498       Retail      0.05      Carlos    3493.511     Gift Card    SAVE10
1499    Wholesale      0.00       Frank    2878.070    Debit Card  FREESHIP

      Returned    OrderID CustomerName  ShippingCost  OrderDate DeliveryDate  \
0            0  REG100000    Cust 6583         43.34 2023-02-23   2023-02-27
1            0  REG100001    Cust 2144          5.30 2024-12-19   2024-12-28
2            0  REG100002    Cust 5998         20.46 2023-05-10   2023-05-19
3            0  REG100003    Cust 7136         27.95 2025-02-26   2025-03-02
4            0  REG100004    Cust 6506          5.73 2023-06-24   2023-06-27
...        ...        ...          ...           ...        ...          ...
1495         0  REG101495    Cust 5227         35.63 2025-02-17   2025-02-22
1496         0  REG101496    Cust 5559         45.93 2024-01-11   2024-01-17
1497         0  REG101497    Cust 8981         35.56 2024-07-27   2024-08-03
1498         0  REG101498    Cust 1824         24.53 2024-12-03   2024-12-10
1499         1  REG101499    Cust 1935         21.05 2025-05-09   2025-05-13

     RegionManager
0             Eric
1           Sophie
2             Ryan
3          Cameron
4             Eric
...            ...
1495         Wendy
1496        Sophie
1497          Eric
1498       Cameron
1499         Wendy

[1500 rows x 19 columns]>

In [6]:
df.describe()

,Date,Quantity,UnitPrice,Discount,TotalPrice,Returned,ShippingCost,OrderDate,DeliveryDate
count,1500,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500,1500
mean,2024-04-07 21:35:02.400000256,10.410667,298.826947,0.073133,2919.994952,0.248000,27.507293,2024-04-07 21:35:02.400000256,2024-04-13 22:36:28.799999744
min,2023-01-01 00:00:00,1.000000,5.520000,0.000000,6.970000,0.000000,5.010000,2023-01-01 00:00:00,2023-01-08 00:00:00
25%,2023-08-20 00:00:00,5.000000,151.020000,0.000000,867.136250,0.000000,16.700000,2023-08-20 00:00:00,2023-08-25 12:00:00
50%,2024-04-08 12:00:00,11.000000,294.740000,0.050000,2174.724000,0.000000,27.100000,2024-04-08 12:00:00,2024-04-15 12:00:00
75%,2024-12-07 06:00:00,15.000000,446.702500,0.100000,4414.723500,0.000000,38.635000,2024-12-07 06:00:00,2024-12-13 06:00:00
max,2025-06-30 00:00:00,20.000000,599.720000,0.150000,11077.000000,1.000000,49.980000,2025-06-30 00:00:00,2025-07-10 00:00:00
std,NaN,5.735732,169.100075,0.055979,2522.789977,0.431996,13.093453,NaN,NaN

In [7]:
df.describe(include="all")

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
count,1500,1500,1500,1500.000000,1500.000000,1500,1500,1500.000000,1500,1500.000000,1500,1130,1500.000000,1500,1500,1500.000000,1500,1500,1500
unique,NaN,5,7,NaN,NaN,4,2,NaN,6,NaN,5,3,NaN,1500,1371,NaN,NaN,NaN,5
top,NaN,East,Tablet,NaN,NaN,Store D,Wholesale,NaN,Carlos,NaN,Online,FREESHIP,NaN,REG100000,Cust 8150,NaN,NaN,NaN,Eric
freq,NaN,311,240,NaN,NaN,400,756,NaN,270,NaN,323,419,NaN,1,4,NaN,NaN,NaN,311
mean,2024-04-07 21:35:02.400000256,NaN,NaN,10.410667,298.826947,NaN,NaN,0.073133,NaN,2919.994952,NaN,NaN,0.248000,NaN,NaN,27.507293,2024-04-07 21:35:02.400000256,2024-04-13 22:36:28.799999744,NaN
min,2023-01-01 00:00:00,NaN,NaN,1.000000,5.520000,NaN,NaN,0.000000,NaN,6.970000,NaN,NaN,0.000000,NaN,NaN,5.010000,2023-01-01 00:00:00,2023-01-08 00:00:00,NaN
25%,2023-08-20 00:00:00,NaN,NaN,5.000000,151.020000,NaN,NaN,0.000000,NaN,867.136250,NaN,NaN,0.000000,NaN,NaN,16.700000,2023-08-20 00:00:00,2023-08-25 12:00:00,NaN
50%,2024-04-08 12:00:00,NaN,NaN,11.000000,294.740000,NaN,NaN,0.050000,NaN,2174.724000,NaN,NaN,0.000000,NaN,NaN,27.100000,2024-04-08 12:00:00,2024-04-15 12:00:00,NaN
75%,2024-12-07 06:00:00,NaN,NaN,15.000000,446.702500,NaN,NaN,0.100000,NaN,4414.723500,NaN,NaN,0.000000,NaN,NaN,38.635000,2024-12-07 06:00:00,2024-12-13 06:00:00,NaN
max,2025-06-30 00:00:00,NaN,NaN,20.000000,599.720000,NaN,NaN,0.150000,NaN,11077.000000,NaN,NaN,1.000000,NaN,NaN,49.980000,2025-06-30 00:00:00,2025-07-10 00:00:00,NaN
std,NaN,NaN,NaN,5.735732,169.100075,NaN,NaN,0.055979,NaN,2522.789977,NaN,NaN,0.431996,NaN,NaN,13.093453,NaN,NaN,NaN

In [8]:
df.shape

(1500, 19)

In [10]:
df.tail()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[ns]
 1   Region         1500 non-null   object
 2   Product        1500 non-null   object
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   object
 6   CustomerType   1500 non-null   object
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   object
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   object
 11  Promotion      1130 non-null   object
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   object
 14  CustomerName   1500 non-null   object
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[ns]
 17  DeliveryDate   1500 non-null   datetime64[ns]
 18  RegionManager  1500 non-null   object
dtypes: datetime64[ns](3), float64(4), int64(2), object(10)
memory usage: 222.8+ KB

In [12]:
df.isnull().sum()
#check for null values

Date               0
Region             0
Product            0
Quantity           0
UnitPrice          0
StoreLocation      0
CustomerType       0
Discount           0
Salesperson        0
TotalPrice         0
PaymentMethod      0
Promotion        370
Returned           0
OrderID            0
CustomerName       0
ShippingCost       0
OrderDate          0
DeliveryDate       0
RegionManager      0
dtype: int64

In [13]:
df['Promotion'] = df['Promotion'].fillna('No Promotion')
#code to fill the null values

In [14]:
df.isnull().sum()

Date             0
Region           0
Product          0
Quantity         0
UnitPrice        0
StoreLocation    0
CustomerType     0
Discount         0
Salesperson      0
TotalPrice       0
PaymentMethod    0
Promotion        0
Returned         0
OrderID          0
CustomerName     0
ShippingCost     0
OrderDate        0
DeliveryDate     0
RegionManager    0
dtype: int64

In [15]:
df["Promotion"].isnull().sum()

np.int64(0)

In [18]:
df.duplicated().sum()
#check for duplicate values

np.int64(0)

In [20]:
df.dtypes
#to check data types

Date             datetime64[ns]
Region                   object
Product                  object
Quantity                  int64
UnitPrice               float64
StoreLocation            object
CustomerType             object
Discount                float64
Salesperson              object
TotalPrice              float64
PaymentMethod            object
Promotion                object
Returned                  int64
OrderID                  object
CustomerName             object
ShippingCost            float64
OrderDate        datetime64[ns]
DeliveryDate     datetime64[ns]
RegionManager            object
dtype: object

In [28]:
df['Date'] = pd.to_datetime(df['Date'])
#changing the data type to their appropriate types

In [32]:
df.dtypes

Date             datetime64[ns]
Region                   object
Product                  object
Quantity                  int64
UnitPrice               float64
StoreLocation            object
CustomerType             object
Discount                float64
Salesperson              object
TotalPrice              float64
PaymentMethod            object
Promotion                object
Returned                  int64
OrderID                  object
CustomerName             object
ShippingCost            float64
OrderDate        datetime64[ns]
DeliveryDate     datetime64[ns]
RegionManager            object
dtype: object

In [33]:
df = df.rename(columns={
    'UnitPrice':'unit price',
    'StoreLocation':'store location',
    'CustomerType':'customer type',
    'Salesperson':'sales person',
    'TotalPrice':'total price',
    'PaymentMethod':'payment method',
    'OrderID':'order id',
    'CustomerName':'customer name',
    'ShippingCost':'shipping cost',
    'OrderDate':'order date',
    'DeliveryDate':'delivery date',
    'RegionManager':'region manager'
})
df.columns

#changing the column names to snake casing

Index(['Date', 'Region', 'Product', 'Quantity', 'unit price', 'store location',
       'customer type', 'Discount', 'sales person', 'total price',
       'payment method', 'Promotion', 'Returned', 'order id', 'customer name',
       'shipping cost', 'order date', 'delivery date', 'region manager'],
      dtype='object')

In [34]:
df.columns = df.columns.str.lower()
df.columns

Index(['date', 'region', 'product', 'quantity', 'unit price', 'store location',
       'customer type', 'discount', 'sales person', 'total price',
       'payment method', 'promotion', 'returned', 'order id', 'customer name',
       'shipping cost', 'order date', 'delivery date', 'region manager'],
      dtype='object')

In [37]:
df[df['total price']<0]
#checking for negative values

Empty DataFrame
Columns: [date, region, product, quantity, unit price, store location, customer type, discount, sales person, total price, payment method, promotion, returned, order id, customer name, shipping cost, order date, delivery date, region manager]
Index: []

In [38]:
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['date', 'region', 'product', 'quantity', 'unit_price', 'store_location',
       'customer_type', 'discount', 'sales_person', 'total_price',
       'payment_method', 'promotion', 'returned', 'order_id', 'customer_name',
       'shipping_cost', 'order_date', 'delivery_date', 'region_manager'],
      dtype='object')

In [39]:
df.head(3)
#checking if everything is ok

,date,region,product,quantity,unit_price,store_location,customer_type,discount,sales_person,total_price,payment_method,promotion,returned,order_id,customer_name,shipping_cost,order_date,delivery_date,region_manager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.0,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.0,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.1,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan

In [40]:
df[(df['discount']<0) | (df['discount']>1)]
#checking if there's any discount values which are not suitable for the table like more that 100% or below 0%

Empty DataFrame
Columns: [date, region, product, quantity, unit_price, store_location, customer_type, discount, sales_person, total_price, payment_method, promotion, returned, order_id, customer_name, shipping_cost, order_date, delivery_date, region_manager]
Index: []

In [41]:
df['discount'].unique()

array([0.  , 0.1 , 0.15, 0.05])

In [42]:
df['discount'].describe()

count    1500.000000
mean        0.073133
std         0.055979
min         0.000000
25%         0.000000
50%         0.050000
75%         0.100000
max         0.150000
Name: discount, dtype: float64

In [43]:
(df == "").sum()
#checkking if there's any empty rows which are filled with spaces

date              0
region            0
product           0
quantity          0
unit_price        0
store_location    0
customer_type     0
discount          0
sales_person      0
total_price       0
payment_method    0
promotion         0
returned          0
order_id          0
customer_name     0
shipping_cost     0
order_date        0
delivery_date     0
region_manager    0
dtype: int64

In [44]:
df.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
#this step clears out the empty rows with spaces and other strings to null values NA

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            1500 non-null   datetime64[ns]
 1   region          1500 non-null   object
 2   product         1500 non-null   object
 3   quantity        1500 non-null   int64
 4   unit_price      1500 non-null   float64
 5   store_location  1500 non-null   object
 6   customer_type   1500 non-null   object
 7   discount        1500 non-null   float64
 8   sales_person    1500 non-null   object
 9   total_price     1500 non-null   float64
 10  payment_method  1500 non-null   object
 11  promotion       1500 non-null   object
 12  returned        1500 non-null   int64
 13  order_id        1500 non-null   object
 14  customer_name   1500 non-null   object
 15  shipping_cost   1500 non-null   float64
 16  order_date      1500 non-null   datetime64[ns]
 17  delivery_date   1500 non-null   datetime64[ns]
 18  region_manager  1500 non-null   object
dtypes: datetime64[ns](3), float64(4), int64(2), object(10)
memory usage: 222.8+ KB

In [50]:
df['region'].unique()
#checking for all the unique values to make sure they're ok

array(['East', 'South', 'North', 'Central', 'West'], dtype=object)

In [52]:
df['customer_type'].unique()

array(['Wholesale', 'Retail'], dtype=object)

In [53]:
df['product'].unique()

array(['Laptop', 'Phone', 'Desk', 'Chair', 'Monitor', 'Tablet', 'Printer'],
      dtype=object)

In [54]:
df['payment_method'].unique()

array(['Online', 'Gift Card', 'Credit Card', 'Debit Card', 'Cash'],
      dtype=object)

In [55]:
df['promotion'].unique()

array(['FREESHIP', 'SAVE10', 'WINTER15', 'No Promotion'], dtype=object)

In [56]:
df['calculated_price'] = df['quantity'] * df['unit_price'] * ( 1 - df['discount'])
#creating a new column to calculate total price to compare with the existing total_price column to know if its right

In [57]:
df['calculated_price'].head()

0    2290.400
1     544.010
2    4361.868
3    5887.746
4    4279.680
Name: calculated_price, dtype: float64

In [58]:
df['total_price'].head()

0    2290.400
1     544.010
2    4361.868
3    5887.746
4    4279.680
Name: total_price, dtype: float64

In [59]:
df['total_price'].unique()

array([2290.4  ,  544.01 , 4361.868, ...,  272.5  , 3493.511, 2878.07 ],
      shape=(1500,))

In [60]:
df['calculated_price'].unique()

array([2290.4  ,  544.01 , 4361.868, ...,  272.5  , 3493.511, 2878.07 ],
      shape=(1500,))

In [61]:
df[abs(df['calculated_price'] - df['total_price']) > 1]
this compares the total_price and our calculated column to find if there's any difference or wrong with total_price

Empty DataFrame
Columns: [date, region, product, quantity, unit_price, store_location, customer_type, discount, sales_person, total_price, payment_method, promotion, returned, order_id, customer_name, shipping_cost, order_date, delivery_date, region_manager, calculated_price]
Index: []

In [62]:
df.head()

,date,region,product,quantity,unit_price,store_location,customer_type,discount,sales_person,total_price,payment_method,promotion,returned,order_id,customer_name,shipping_cost,order_date,delivery_date,region_manager,calculated_price
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.400
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.010
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4361.868
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,5887.746
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.680

In [63]:
df = df.drop(columns='calculated_price')
#now we can drop the column we created for checking

In [64]:
df.head()

,date,region,product,quantity,unit_price,store_location,customer_type,discount,sales_person,total_price,payment_method,promotion,returned,order_id,customer_name,shipping_cost,order_date,delivery_date,region_manager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [66]:
df['delivery_days'] = (df['delivery_date'] - df['order_date']).dt.days
#this creates a new column with the delivery days from ordering to delivery

In [67]:
df['delivery_days'].head()

0    4
1    9
2    9
3    4
4    3
Name: delivery_days, dtype: int64

In [68]:
df.head()

,date,region,product,quantity,unit_price,store_location,customer_type,discount,sales_person,total_price,payment_method,promotion,returned,order_id,customer_name,shipping_cost,order_date,delivery_date,region_manager,delivery_days
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,4
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,9
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,9
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,4
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,3

In [69]:
df[df['delivery_days'] < 1]
#checking if there's any days which is in negative value to find an error in the columns

Empty DataFrame
Columns: [date, region, product, quantity, unit_price, store_location, customer_type, discount, sales_person, total_price, payment_method, promotion, returned, order_id, customer_name, shipping_cost, order_date, delivery_date, region_manager, delivery_days]
Index: []

In [70]:
df.info()
#finally checking for some things to know if everythings okay

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            1500 non-null   datetime64[ns]
 1   region          1500 non-null   object
 2   product         1500 non-null   object
 3   quantity        1500 non-null   int64
 4   unit_price      1500 non-null   float64
 5   store_location  1500 non-null   object
 6   customer_type   1500 non-null   object
 7   discount        1500 non-null   float64
 8   sales_person    1500 non-null   object
 9   total_price     1500 non-null   float64
 10  payment_method  1500 non-null   object
 11  promotion       1500 non-null   object
 12  returned        1500 non-null   int64
 13  order_id        1500 non-null   object
 14  customer_name   1500 non-null   object
 15  shipping_cost   1500 non-null   float64
 16  order_date      1500 non-null   datetime64[ns]
 17  delivery_date   1500 non-null   datetime64[ns]
 18  region_manager  1500 non-null   object
 19  delivery_days   1500 non-null   int64
dtypes: datetime64[ns](3), float64(4), int64(3), object(10)
memory usage: 234.5+ KB

In [71]:
df.isnull().sum()

date              0
region            0
product           0
quantity          0
unit_price        0
store_location    0
customer_type     0
discount          0
sales_person      0
total_price       0
payment_method    0
promotion         0
returned          0
order_id          0
customer_name     0
shipping_cost     0
order_date        0
delivery_date     0
region_manager    0
delivery_days     0
dtype: int64

In [72]:
df.to_csv('product_sales_region_cleaned.csv', index=False)